### ISSUE TITLE
callback_uri typo?

### ISSUE THREAD

**Issue by nathans** [xray7224/PyPump#41]
After upgrading to 0.1.7a, I am unable to complete registration. Error: "PyPump has no attribute 'callback_uri'"

Looks like there is a typo at https://github.com/xray7224/PyPump/blob/4752b954d6fd4f890772330b76b7fa0af603a447/pypump/pypump.py#L68

I believe self.callback_ui is supposed to be self.callback_uri
